test release e deploy dal branch 406

diff --git a/.github/workflows/release-quarkus-ms.yml b/.github/workflows/release-quarkus-ms.yml
--- a/.github/workflows/release-quarkus-ms.yml
+++ b/.github/workflows/release-quarkus-ms.yml
@@ -46,13 +46,13 @@ jobs:
         uses: actions/checkout@v3
         with:
           token: ${{ secrets.PAT_BOT }}
-#      - name: Check default branch
-          #        run: |
-          #default_branch=$(git remote show origin | awk '/HEAD branch/ {print $3}')
-            #if [ "${{ github.ref }}" != "refs/heads/$default_branch" ]; then
-            #echo "Error: Workflow must be triggered from default branch ($default_branch)." >&2
-          #exit 1
-          #fi
+      - name: Check default branch
+        run: |
+          default_branch=$(git remote show origin | awk '/HEAD branch/ {print $3}')
+          if [ "${{ github.ref }}" != "refs/heads/$default_branch" ]; then
+            echo "Error: Workflow must be triggered from default branch ($default_branch)." >&2
+            exit 1
+          fi
       - name: Java Setup
         uses: actions/setup-java@v3
         with:
