test: trying to build ms with rootless image
test: change name img

test: change name img (build e release)

test: change name img - pdnd-aws-runner-microservices:PA-376 (build e release)

setup git credentials (#20)

diff --git a/.github/workflows/release-quarkus-ms.yml b/.github/workflows/release-quarkus-ms.yml
--- a/.github/workflows/release-quarkus-ms.yml
+++ b/.github/workflows/release-quarkus-ms.yml
@@ -24,7 +24,7 @@ jobs:
           base64_encoded_ca_crt: ${{ secrets.K8S_CA_CRT }}
           name: ${{ github.event.repository.name }}
           namespace: prod-github-runners
-          image: gateway.private.pdnd.pagopa.it/pagopa/pdnd-aws-runner-microservices:v1.1.3
+          image: gateway.private.pdnd.pagopa.it/pagopa/pdnd-aws-runner-microservices:PA-376
           service_account: github-actions-sa
           docker_enabled: true
           image_pull_secret: regcred
@@ -46,13 +46,13 @@ jobs:
         uses: actions/checkout@v3
         with:
           token: ${{ secrets.PAT_BOT }}
-      - name: Check default branch
-        run: |
-          default_branch=$(git remote show origin | awk '/HEAD branch/ {print $3}')
-          if [ "${{ github.ref }}" != "refs/heads/$default_branch" ]; then
-            echo "Error: Workflow must be triggered from default branch ($default_branch)." >&2
-            exit 1
-          fi
+        ###      - name: Check default branch
+          ###run: |
+          ###default_branch=$(git remote show origin | awk '/HEAD branch/ {print $3}')
+            ###if [ "${{ github.ref }}" != "refs/heads/$default_branch" ]; then
+            ###echo "Error: Workflow must be triggered from default branch ($default_branch)." >&2
+          ###exit 1
+###          fi
       - name: Java Setup
         uses: actions/setup-java@v3
         with:
@@ -90,7 +90,6 @@ jobs:
           bot_name: ${{ env.BOT_USERNAME }}
       - name: Set environment variable
         run: echo "RELEASE_TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
-        ##run: echo "RELEASE_TAG=$(git describe --tags --always --long --match 'refs/tags/*')" >> $GITHUB_ENV
     outputs:
       release_tag: ${{ env.RELEASE_TAG }}
   destroy_runner:
