fix: Check default branch

diff --git a/.github/workflows/release-quarkus-ms.yml b/.github/workflows/release-quarkus-ms.yml
--- a/.github/workflows/release-quarkus-ms.yml
+++ b/.github/workflows/release-quarkus-ms.yml
@@ -48,10 +48,11 @@ jobs:
           token: ${{ secrets.PAT_BOT }}
       - name: Check default branch
         run: |
-            if [ "${{ github.ref }}" != "$(format 'refs/heads/{0}' ${{ github.event.repository.default_branch }})" ]; then
-            echo "Error: Workflow must be triggered from default branch (${{ github.event.repository.default_branch }})." >&2
+          default_branch=$(git remote show origin | awk '/HEAD branch/ {print $3}')
+          if [ "${{ github.ref }}" != "refs/heads/$default_branch" ]; then
+            echo "Error: Workflow must be triggered from default branch ($default_branch)." >&2
             exit 1
-            fi
+          fi
       - name: Java Setup
         uses: actions/setup-java@v3
         with:
