fix: updated version undeploy-gh-runner
fix: updated version release-quarkus-ms.yml and deploy-quarkus-ms.yml

fix: restore check defaut branch

diff --git a/.github/workflows/release-quarkus-ms.yml b/.github/workflows/release-quarkus-ms.yml
--- a/.github/workflows/release-quarkus-ms.yml
+++ b/.github/workflows/release-quarkus-ms.yml
@@ -17,7 +17,7 @@ jobs:
     steps:
       - name: Create Runner
         id: create_runner
-        uses: pagopa/pdnd-github-actions/deploy-gh-runner@v1.0.1
+        uses: pagopa/pdnd-github-actions/deploy-gh-runner@f2324991919536414cf6ecef62d1dbaeadea584e
         with:
           api_server: ${{ vars.K8S_API_SERVER }}
           access_token: ${{ secrets.GH_ACTIONS_SA_ACCESS_TOKEN }}
@@ -46,13 +46,13 @@ jobs:
         uses: actions/checkout@v3
         with:
           token: ${{ secrets.PAT_BOT }}
-        ###      - name: Check default branch
-          ###run: |
-          ###default_branch=$(git remote show origin | awk '/HEAD branch/ {print $3}')
-            ###if [ "${{ github.ref }}" != "refs/heads/$default_branch" ]; then
-            ###echo "Error: Workflow must be triggered from default branch ($default_branch)." >&2
-          ###exit 1
-###          fi
+      - name: Check default branch
+        run: |
+          default_branch=$(git remote show origin | awk '/HEAD branch/ {print $3}')
+            if [ "${{ github.ref }}" != "refs/heads/$default_branch" ]; then
+            echo "Error: Workflow must be triggered from default branch ($default_branch)." >&2
+          exit 1
+          fi
       - name: Java Setup
         uses: actions/setup-java@v3
         with:
@@ -101,7 +101,7 @@ jobs:
     steps:
       - name: Destroy Runner
         id: destroy_runner
-        uses: pagopa/pdnd-github-actions/undeploy-gh-runner@v1.0.1
+        uses: pagopa/pdnd-github-actions/undeploy-gh-runner@f2324991919536414cf6ecef62d1dbaeadea584e
         with:
           api_server: ${{ vars.K8S_API_SERVER }}
           access_token: ${{ secrets.GH_ACTIONS_SA_ACCESS_TOKEN }}
